upstream php_backend {
    server php_backend:9000;
}

server {
    listen 80;
    server_name localhost;
    root /var/www/html;

    index index.php index.html;
    # Custom error pages
    error_page 404 /var/www/html/errorFolder/404.html;
    error_page 500 502 503 504 /var/www/html/errorFolder/500.html;

    # Location for error pages (prevent them from being processed as PHP)
    location ~ ^/(404|500)\.html$ {
        internal;
    }

    # Logging configuration
    access_log /var/www/html/logs/access.log;
    error_log /var/www/html/logs/error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        fastcgi_pass php_backend;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}